name: Repack Webex .deb (XWayland + AppArmor)

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday morning

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget fakeroot dpkg-dev

      - name: Download Webex .deb
        run: |
          wget -O Webex.deb "https://binaries.webex.com/WebexDesktop-Ubuntu-Official-Package/Webex.deb"

      - name: Repack with patches
        run: bash scripts/repack-webex.sh

      - name: Upload rebuilt .deb as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Webex-fixed-deb
          path: Webex-fixed.deb

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Webex Repack $(date +'%Y-%m-%d')"
          tag_name: "webex-$(date +'%Y-%m-%d')"
          body: |
            🚀 **Automated Webex Repack Build**
            - Based on the latest official Cisco `.deb`
            - Forces X11/XWayland mode
            - Adds AppArmor profile at `/etc/apparmor.d/Webex`

            ✅ Build Date: $(date +'%Y-%m-%d')
          files: Webex-fixed.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
