name: Repack Webex .deb (XWayland + AppArmor)

on:
  push:
    branches: [ master ]
    tags:
      - "webex-*"
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday morning

permissions:
  contents: write  # Required by action-gh-release to publish releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget fakeroot dpkg-dev

      - name: Download Webex .deb
        run: |
          wget -O Webex.deb "https://binaries.webex.com/WebexDesktop-Ubuntu-Official-Package/Webex.deb"

      - name: Repack with patches
        run: bash scripts/repack-webex.sh

      - name: Generate SHA256 checksum
        run: sha256sum Webex-fixed.deb | tee checksum.txt

      - name: Upload rebuilt .deb as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Webex-fixed-deb
          path: Webex-fixed.deb

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag' || github.event_name == 'workflow_dispatch'
        with:
          name: "Webex Repack - ${{ github.ref_name }}"
          tag_name: "${{ github.ref_name || format('webex-{0}', github.run_number) }}"
          body: |
            🚀 **Automated Webex Repack Build**
            ✅ Built on: ${{ github.run_id }}
            
            **Includes:**
            - Forces Webex to run under XWayland
            - Adds AppArmor profile `/etc/apparmor.d/Webex`
            - Automatic rebuild and repackaging of latest .deb

            **SHA256 checksum:**
            ```
            ${{ steps.checksum.outputs.sha256 }}
            ```
          files: |
            Webex-fixed.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
