name: Repack Webex .deb (XWayland + AppArmor)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday morning

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget fakeroot dpkg-dev

      - name: Download Webex .deb
        run: |
          wget -O Webex.deb "https://binaries.webex.com/WebexDesktop-Ubuntu-Official-Package/Webex.deb"

      - name: Repack with patches
        run: bash scripts/repack-webex.sh

      - name: Upload rebuilt .deb
        uses: actions/upload-artifact@v4
        with:
          name: Webex-fixed-deb
          path: Webex-fixed.deb

